{% set name = "lime" %}
{% set version = "0.2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 76960e4f055feb53e89b5022383bafc87b63f25bac6265984b0a333d1a57f781

build:
  skip: true  # [py<35]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python 
    - pip
    - setuptools
    - wheel
  run:
    - python
    - matplotlib-base
    - numpy
    - scipy
    - tqdm
    - scikit-learn >=0.18
    - scikit-image >=0.12

test:
  source_files:
    - lime/tests
  imports:
    - lime
  commands:
    - pip check
    # The two first tests are deactivated because np.array_equal seems to have been used incorrectly in tests. It compares two nested lists
    # such as [[0, 8], [2], [4], [6]] and [[0, 8], [2], [4], [6]], which are equal but numpy fails to assert this. this is due to the [ 0, 8] 
    # element of the list, which is of different length. np.array_equal is not used anywhere in the actual code. The third test fails randomly, 
    # possibly because it uses random seed.
    - python -m pytest lime/tests -vv -k "not (test_indexed_string_callable or test_indexed_string_regex or test_lime_explainer_entropy_discretizer)"
  requires:
    - pip
    - pytest

about:
  home: https://github.com/marcotcr/lime
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Explaining the predictions of any machine learning classifier
  description: |
    This project is about explaining what machine learning classifiers (or models) 
    are doing. At the moment, it supports explaining individual predictions for text 
    classifiers or classifiers that act on tables (numpy arrays of numerical or 
    categorical data) or images, with a package called lime (short for local 
    interpretable model-agnostic explanations). 
  doc_url: https://lime-ml.readthedocs.io/
  dev_url: https://github.com/marcotcr/lime

extra:
  recipe-maintainers:
    - proinsias
    - ocefpaf
