{% set name = "lime" %}
{% set version = "0.1.1.30" %}
{% set sha256 = "6210d45fb3be1cf0e49727a39097701fbe06e3e534aa9e0824a4e1dca3132840" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - lime

about:
  home: https://github.com/marcotcr/lime
  license: BSD-2-Clause
  license_family: BSD
#  license_file: LICENSE  # When added to MANIFEST.in – marcotcr/lime#40
  summary: 'Explaining the predictions of any machine learning classifier'
  doc_url: https://lime-ml.readthedocs.io/
  dev_url: https://github.com/marcotcr/lime

extra:
  recipe-maintainers:
    - proinsias
