travis:
  secure:
    BINSTAR_TOKEN: QzIOsqcx6uAwv3GAKNGGgGZXaMvB3oRnmP17YApvboF/Q5Unah9IRB3fSgZ+FG+82oAxgK6GLq3yz4yRT9qCsuPpYJgo2ixSRoWfPMny6Z6j34pV+7ibDVRfzO9l39suYBvB9jwSiMA7vqjXVCU/Datj3Oi5257XfyownGCsMDpxLOmjaxS86YX/h0arClfV6VbhEqz+XjuGl1SfXp83/oO3gKCfitQOTATZODgl+/Ixcsr2XWvdIRYE+DsRgRDLAiSEviFtiupe5N3lxNA6/6q3Mqdy8Czt9RiyVHuDGRroCo+Dz+2QOUSgjhJ2quN3WOSRiwJYUrrzkrZloUlF9vo6S/zKf9xJTAdXdfSi1X+UWuK8DCwmDfofwofbmG4oP0xRb6cEe6S9OKNXKLJBGd6cacndnqADh3Gn2y6W6sYeluqXpla2euEeesRtHDI8DNQlgswxN6+Vqz8jsrWraLMmo7dVoSUvvEmbtWQNAtppWf3I/sSIKsmXqpavYUT7lzWBGy757mABR2j+49/c/I/xkQytoKUc3sRTNEo6hZz84ro0i9YDNJrTYeYW6LLHyOmB/HB4cZLaltjZmnBYprsiogkv/oNxGqOVh1yq25fe9eX1/1yZZZaX3y3x27g0LiBVHSN9JnM6Vle9MhH7GOO1IzXx/R4MrQKbeWrZc2s=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
