travis:
  secure:
    BINSTAR_TOKEN: ZqnumzG5ZWsnKm9T0XriAUDI20Uu3IQlzA8JQfMbnHh8mU/dNumd2DaN59YzZEEH+z5J5ToKndmN//vDthG3p6/h+zijVHYQR5TzCD29+eKNupvt0dcou4Ehh2FmcgiPTC5PQ5nijh0nfKGzgnQ9NCxqupD0PaH4bl89qGiE31t0yLYIE2/cKZT5uZ4mfyYqHlTi5e+OaPIrFbHCNPvVr5ZDeFd3OQHP2ncn1foItHy3WzGminVMMuFAGeRIKLoLW0XJGx+GSn8fP/Hca6AXA0fnD4OeRnBIQiJnI4qGMqnnmZ3eJP+QWSjBAWqI/U8YNokutfMX2wRw+z1f49oNR9zAWO3MnOcgk5LXfX6t6VHwCzleWmsjn9gwH8AOygafVVFyu7Q9QNygzzOImy5fftm2tDrqC0HBSMpLzWyc25nvDeQFMzzUX5oudEP4K/Fdrn7du/B06y2ZjFP41gcC6qUcJ6c7JzhIYCPm1QD16airbBflDT98zO2s8YHooDksymsj6/Cgi0EIlqDpojtAicD7D70lO/kShuCsv1y29/D7pX37lsOB36QGPZjBsZ5hYu/qwwqqQYlaTiqAvPHwFxsVOoXasWmc04Exm/rrngrIOOglczW2ml1Wt1ZkD8NRcHp1AlGtxfWzD2tudQg1TYGE4Uzd0OT+CaCypWnnq4M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
